version: '3.8'

services:
  app:
    build: .
    container_name: meu-app
    env_file:
      - .env # Carrega as variáveis do arquivo .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: meu-banco
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
