export const mock = [
  // ------------------ AVENTURA ------------------
  {
    id: "1",
    name: "O Último Feiticeiro",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Aventura", "Magia", "Épico"],
    votes: 0,
    commentsTotal: 0,
    views: 22400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "2",
    name: "As Chamas de Veridion",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Fantasia", "Conflito", "Viagem"],
    votes: 0,
    commentsTotal: 0,
    views: 31000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "3",
    name: "Ilhas Perdidas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Exploração", "Mistério"],
    votes: 0,
    commentsTotal: 0,
    views: 8200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "4",
    name: "Caminho dos Heróis",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Heróis", "Conquista"],
    votes: 0,
    commentsTotal: 0,
    views: 19700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "5",
    name: "Montanhas de Gelo",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Sobrevivência", "Frio"],
    votes: 0,
    commentsTotal: 0,
    views: 14300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "6",
    name: "Sob o Sol Escarlate",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Deserto", "Guerras"],
    votes: 0,
    commentsTotal: 0,
    views: 9100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "7",
    name: "O Navegador das Estrelas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Espaço", "Exploração"],
    votes: 0,
    commentsTotal: 0,
    views: 18700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "8",
    name: "Ruínas do Deserto",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Aventura",
    tags: ["Ruínas", "Segredos"],
    votes: 0,
    commentsTotal: 0,
    views: 6300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },

  // ------------------ ROMANCE ------------------
  {
    id: "9",
    name: "Corações em Cinzas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Drama", "Paixão"],
    votes: 0,
    commentsTotal: 0,
    views: 4200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "10",
    name: "Entre Dois Mundos",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Escolhas", "Destino"],
    votes: 0,
    commentsTotal: 0,
    views: 12100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "11",
    name: "Amor em Ruínas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Tragédia", "Intenso"],
    votes: 0,
    commentsTotal: 0,
    views: 7100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "12",
    name: "Promessas ao Vento",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Promessas", "Esperança"],
    votes: 0,
    commentsTotal: 0,
    views: 8900,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "13",
    name: "Sob as Estrelas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Sonhos", "Juventude"],
    votes: 0,
    commentsTotal: 0,
    views: 15400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "14",
    name: "Amor Proibido",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Proibido", "Segredo"],
    votes: 0,
    commentsTotal: 0,
    views: 9700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "15",
    name: "Laços Eternos",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Compromisso", "Eterno"],
    votes: 0,
    commentsTotal: 0,
    views: 20100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "16",
    name: "O Último Beijo",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Romance",
    tags: ["Despedida", "Emoção"],
    votes: 0,
    commentsTotal: 0,
    views: 7200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },

  // ------------------ POEMA ------------------
  {
    id: "17",
    name: "Versos ao Luar",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Romântico", "Noite"],
    votes: 0,
    commentsTotal: 0,
    views: 13400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "18",
    name: "O Canto das Ondas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Mar", "Natureza"],
    votes: 0,
    commentsTotal: 0,
    views: 4200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "19",
    name: "Poemas de Inverno",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Frio", "Saudade"],
    votes: 0,
    commentsTotal: 0,
    views: 5800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "20",
    name: "Cores da Alma",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Sentimentos", "Abstrato"],
    votes: 0,
    commentsTotal: 0,
    views: 9400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "21",
    name: "Som do Silêncio",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Reflexão", "Paz"],
    votes: 0,
    commentsTotal: 0,
    views: 7200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "22",
    name: "Chuva de Estrelas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Esperança", "Brilho"],
    votes: 0,
    commentsTotal: 0,
    views: 10100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "23",
    name: "Lágrimas e Sorrisos",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Dualidade", "Vida"],
    votes: 0,
    commentsTotal: 0,
    views: 6200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "24",
    name: "Canções de Areia",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Poema",
    tags: ["Tempo", "Memória"],
    votes: 0,
    commentsTotal: 0,
    views: 8300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },

  // ------------------ FANTASIA ------------------
  {
    id: "25",
    name: "A Canção da Lua",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Mágico", "Romance"],
    votes: 0,
    commentsTotal: 0,
    views: 13400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "26",
    name: "Sombras de Aelorian",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Sombras", "Mistério"],
    votes: 0,
    commentsTotal: 0,
    views: 9400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "27",
    name: "O Despertar de Lunara",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Despertar", "Profecia"],
    votes: 0,
    commentsTotal: 0,
    views: 19700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "28",
    name: "Reino de Vidro",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Reino", "Fragilidade"],
    votes: 0,
    commentsTotal: 0,
    views: 7600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "29",
    name: "Herança de Sombras",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Legado", "Escuridão"],
    votes: 0,
    commentsTotal: 0,
    views: 5200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "30",
    name: "Fragmentos do Infinito",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Cosmos", "Eterno"],
    votes: 0,
    commentsTotal: 0,
    views: 30100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "31",
    name: "A Coroa e a Lâmina",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Realeza", "Conflito"],
    votes: 0,
    commentsTotal: 0,
    views: 22100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "32",
    name: "O Jardim das Almas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Fantasia",
    tags: ["Misticismo", "Natureza"],
    votes: 0,
    commentsTotal: 0,
    views: 6700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },

  // ------------------ COMÉDIA ------------------
  {
    id: "33",
    name: "Trapalhadas no Reino",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Trapalhadas", "Reino"],
    votes: 0,
    commentsTotal: 0,
    views: 8800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "34",
    name: "Um Ogro Apaixonado",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Ogro", "Amor"],
    votes: 0,
    commentsTotal: 0,
    views: 12400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "35",
    name: "A Taverna do Riso",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Humor", "Bebedeira"],
    votes: 0,
    commentsTotal: 0,
    views: 5300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "36",
    name: "Dragões de Cueca",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Dragões", "Zoeira"],
    votes: 0,
    commentsTotal: 0,
    views: 9600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "37",
    name: "Confusões em Lunara",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Confusão", "Cidade"],
    votes: 0,
    commentsTotal: 0,
    views: 14200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "38",
    name: "Amor e Piadas",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Amor", "Humor"],
    votes: 0,
    commentsTotal: 0,
    views: 7100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: true
  },
  {
    id: "39",
    name: "O Palhaço da Corte",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Corte", "Palhaço"],
    votes: 0,
    commentsTotal: 0,
    views: 9300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  },
  {
    id: "40",
    name: "Feitiços Engraçados",
    cover: "https://placehold.co/300x420",
    sinopse: "",
    author: "Desconhecido",
    genre: "Comédia",
    tags: ["Feitiços", "Comédia"],
    votes: 0,
    commentsTotal: 0,
    views: 6200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "published",
    mature: false
  }
];

export const notification = [
  { id: 1, type: 'vote', message: 'Alguém votou na sua obra "Ecos do Passado"', read: false, date: new Date().toISOString(), link: '/books/1/chapters' },
  { id: 2, type: 'comment', message: 'Novo comentário em "A Última Profecia"', read: false, date: new Date(Date.now() - 60_000).toISOString(), link: '/books/2/chapters' },
  { id: 3, type: 'follower', message: 'Lunara começou a te seguir', read: false, date: new Date(Date.now() - 2*60_000).toISOString(), link: '/users/Lunara' },
  { id: 4, type: 'directMessage', message: 'Nova mensagem direta de Arcturus', read: false, date: new Date(Date.now() - 3*60_000).toISOString(), link: '/messages' },
  { id: 5, type: 'premium', message: 'Seu Premium expira em 3 dias', read: false, date: new Date(Date.now() - 4*60_000).toISOString(), link: '/account/premium' },
  { id: 6, type: 'author', message: 'Nova obra publicada por @Lunara: "Sombras da Lua"', read: false, date: new Date(Date.now() - 5*60_000).toISOString(), link: '/books/3/chapters' },
  { id: 7, type: 'system', message: 'O Lunar Contest começou! Confira as regras', read: false, date: new Date(Date.now() - 6*60_000).toISOString(), link: '/contest' },
  { id: 8, type: 'vote', message: 'Alguém votou na sua obra "O Guardião"', read: false, date: new Date(Date.now() - 7*60_000).toISOString(), link: '/books/4/chapters' },
  { id: 9, type: 'comment', message: 'Novo comentário em "Crônicas do Eclipse"', read: false, date: new Date(Date.now() - 8*60_000).toISOString(), link: '/books/5/chapters' },
  { id: 10, type: 'admin', message: 'Atualização de sistema: melhorias de performance', read: false, date: new Date(Date.now() - 9*60_000).toISOString(), link: '/updates' },
  { id: 11, type: 'follower', message: 'Orion começou a te seguir', read: false, date: new Date(Date.now() - 10*60_000).toISOString(), link: '/users/Orion' },
  { id: 12, type: 'directMessage', message: 'Nova mensagem direta de Selene', read: false, date: new Date(Date.now() - 11*60_000).toISOString(), link: '/messages' },
  { id: 13, type: 'premium', message: 'Promoção: Renove seu Premium e ganhe 20% off', read: false, date: new Date(Date.now() - 12*60_000).toISOString(), link: '/account/premium' },
  { id: 14, type: 'author', message: 'Nova obra publicada por @Arcturus: "O Códice"', read: false, date: new Date(Date.now() - 13*60_000).toISOString(), link: '/books/6/chapters' },
  { id: 15, type: 'system', message: 'Notas de atualização: nova interface de notificações', read: false, date: new Date(Date.now() - 14*60_000).toISOString(), link: '/updates' },
  { id: 16, type: 'vote', message: 'Alguém votou na sua obra "A Jornada do Herói"', read: false, date: new Date(Date.now() - 15*60_000).toISOString(), link: '/books/7/chapters' },
  { id: 17, type: 'comment', message: 'Novo comentário em "Crônicas da Aurora"', read: false, date: new Date(Date.now() - 16*60_000).toISOString(), link: '/books/8/chapters' },
  { id: 18, type: 'admin', message: 'Sistema em manutenção prevista para amanhã', read: false, date: new Date(Date.now() - 17*60_000).toISOString(), link: '/updates' },
  { id: 19, type: 'follower', message: 'Lyra começou a te seguir', read: false, date: new Date(Date.now() - 18*60_000).toISOString(), link: '/users/Lyra' },
  { id: 20, type: 'directMessage', message: 'Nova mensagem direta de NovaUser', read: false, date: new Date(Date.now() - 19*60_000).toISOString(), link: '/messages' },
  { id: 21, type: 'premium', message: 'Seu Premium está ativo até 15/10', read: false, date: new Date(Date.now() - 20*60_000).toISOString(), link: '/account/premium' },
  { id: 22, type: 'author', message: 'Nova obra publicada por @NovaUser: "Lendas do Vazio"', read: false, date: new Date(Date.now() - 21*60_000).toISOString(), link: '/books/9/chapters' },
  { id: 23, type: 'system', message: 'Evento Lunar: desafio de escrita começando amanhã', read: false, date: new Date(Date.now() - 22*60_000).toISOString(), link: '/events' },
  { id: 24, type: 'vote', message: 'Alguém votou na sua obra "O Último Feiticeiro"', read: false, date: new Date(Date.now() - 23*60_000).toISOString(), link: '/books/10/chapters' },
  { id: 25, type: 'comment', message: 'Novo comentário em "Diário das Estrelas"', read: false, date: new Date(Date.now() - 24*60_000).toISOString(), link: '/books/11/chapters' },
  { id: 26, type: 'follower', message: 'NovaUser começou a te seguir', read: false, date: new Date(Date.now() - 25*60_000).toISOString(), link: '/users/NovaUser' },
  { id: 27, type: 'directMessage', message: 'Nova mensagem direta de Arcturus', read: false, date: new Date(Date.now() - 26*60_000).toISOString(), link: '/messages' },
  { id: 28, type: 'premium', message: 'Seu Premium expirará em 2 dias', read: false, date: new Date(Date.now() - 27*60_000).toISOString(), link: '/account/premium' },
  { id: 29, type: 'author', message: 'Nova obra publicada por @Lyra: "Fragmentos do Caos"', read: false, date: new Date(Date.now() - 28*60_000).toISOString(), link: '/books/12/chapters' },
  { id: 30, type: 'system', message: 'Atualização de sistema: performance melhorada', read: false, date: new Date(Date.now() - 29*60_000).toISOString(), link: '/updates' },
]
