export const genres = [
  "Ação",
  "Aventura",
  "Romance",
  "Romance Contemporâneo",
  "Romance Histórico",
  "Dark Romance",
  "Suspense",
  "Suspense Psicológico",
  "Terror",
  "Horror Cósmico",
  "Thriller",
  "Drama",
  "Comédia",
  "Fantasia",
  "Fantasia Épica",
  "Fantasia Urbana",
  "Alta Fantasia",
  "Baixa Fantasia",
  "Dark Fantasia",
  "Ficção Científica",
  "Cyberpunk",
  "Steampunk",
  "Space Opera",
  "Distopia",
  "Utopia",
  "Pós-Apocalíptico",
  "Mistério",
  "Policial",
  "Investigativo",
  "Noir",
  "Crime",
  "Slice of Life",
  "Literatura Clássica",
  "Literatura Contemporânea",
  "Realismo Mágico",
  "Sobrenatural",
  "Mitologia",
  "Lenda Medieval",
  "Histórico",
  "Épico Histórico",
  "Biografia",
  "Autobiografia",
  "Memórias",
  "Ensaio",
  "Crônica",
  "Poesia",
  "Haikai",
  "Slam",
  "Prosa Poética",
  "Espiritualidade",
  "Autoajuda",
  "Erótico",
  "New Adult",
  "Young Adult (YA)",
  "Infantojuvenil",
  "Infantil",
  "Fantasia Infantil",
  "Aventura Juvenil",
  "LGBTQIA+",
  "Ficção Feminina",
  "Ficção Histórica Feminina",
  "Romance de Época",
  "Romance Paranormal",
  "LitRPG",
  "Webnovel",
  "Light Novel",
  "Fantasia Sombria",
  "Psicológico",
  "Gótico",
  "Romance Gótico",
  "Conto",
  "Novela (narrativa)",
  "Antologia",
  "Satírico",
  "Paródia",
  "Ficção Filosófica",
  "Ficção Política",
  "Religioso",
  "Experimental",
  "Minimalista",
  "Narrativa Não Linear"
];